extend type Achievement {
  """
  ✨ List `UserAchievement` objects in a one-to-many relationship (where `UserAchievement`.`achievement` is this object).
  """
  userAchievements_on_achievement(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAchievement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAchievement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAchievement_Having
  ): [UserAchievement!]! @fdc_generated(from: "UserAchievement.achievement", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `UserAchievement` as the join table (a `UserAchievement` object exists where its `achievement` is this and its `user` is that).
  """
  users_via_UserAchievement(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAchievement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAchievement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAchievement_Having
  ): [User!]! @fdc_generated(from: "UserAchievement", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Achievement", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Achievement` table.
  """
  _count: Int! @fdc_generated(from: "Achievement.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Achievement` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Achievement.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Achievement` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Achievement.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Achievement` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Achievement.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Achievement` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Achievement.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Achievement.id", purpose: GLOBAL_ID)
}
extend type Mission {
  """
  ✨ List `Submission` objects in a one-to-many relationship (where `Submission`.`mission` is this object).
  """
  submissions_on_mission(
    """
    Filter condition to narrow down the query results.
    """
    where: Submission_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Submission_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Submission_Having
  ): [Submission!]! @fdc_generated(from: "Submission.mission", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Mission", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Mission` table.
  """
  _count: Int! @fdc_generated(from: "Mission.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `dataSchema` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dataSchema_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.dataSchema", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `experienceReward` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  experienceReward_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.experienceReward", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `locationHint` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  locationHint_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.locationHint", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `pointsReward` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pointsReward_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.pointsReward", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mission` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mission.title", purpose: QUERY_COUNT)
  """
  ✨ Sum the `experienceReward` field in the `Mission` table.
  """
  experienceReward_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Mission.experienceReward", purpose: QUERY_SUM)
  """
  ✨ Sum the `pointsReward` field in the `Mission` table.
  """
  pointsReward_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Mission.pointsReward", purpose: QUERY_SUM)
  """
  ✨ Average the `experienceReward` field in the `Mission` table.
  """
  experienceReward_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Mission.experienceReward", purpose: QUERY_AVG)
  """
  ✨ Average the `pointsReward` field in the `Mission` table.
  """
  pointsReward_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Mission.pointsReward", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Mission` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Mission.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `Mission` table.
  """
  dueDate_min: Timestamp @fdc_generated(from: "Mission.dueDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `experienceReward` field in the `Mission` table.
  """
  experienceReward_min: Int @fdc_generated(from: "Mission.experienceReward", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `pointsReward` field in the `Mission` table.
  """
  pointsReward_min: Int @fdc_generated(from: "Mission.pointsReward", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Mission` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Mission.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `Mission` table.
  """
  dueDate_max: Timestamp @fdc_generated(from: "Mission.dueDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `experienceReward` field in the `Mission` table.
  """
  experienceReward_max: Int @fdc_generated(from: "Mission.experienceReward", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `pointsReward` field in the `Mission` table.
  """
  pointsReward_max: Int @fdc_generated(from: "Mission.pointsReward", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Mission.id", purpose: GLOBAL_ID)
}
extend type Submission {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Submission", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Submission` table.
  """
  _count: Int! @fdc_generated(from: "Submission.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `missionId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  missionId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.missionId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `submittedData` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  submittedData_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.submittedData", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Submission` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Submission.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Submission` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Submission.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Submission` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Submission.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Submission.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Submission` objects in a one-to-many relationship (where `Submission`.`user` is this object).
  """
  submissions_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Submission_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Submission_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Submission_Having
  ): [Submission!]! @fdc_generated(from: "Submission.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserAchievement` objects in a one-to-many relationship (where `UserAchievement`.`user` is this object).
  """
  userAchievements_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAchievement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAchievement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAchievement_Having
  ): [UserAchievement!]! @fdc_generated(from: "UserAchievement.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Achievement` objects using `UserAchievement` as the join table (a `UserAchievement` object exists where its `user` is this and its `achievement` is that).
  """
  achievements_via_UserAchievement(
    """
    Filter condition to narrow down the query results.
    """
    where: UserAchievement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserAchievement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserAchievement_Having
  ): [Achievement!]! @fdc_generated(from: "UserAchievement", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `level` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  level_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.level", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `points` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  points_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.points", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Sum the `level` field in the `User` table.
  """
  level_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.level", purpose: QUERY_SUM)
  """
  ✨ Sum the `points` field in the `User` table.
  """
  points_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.points", purpose: QUERY_SUM)
  """
  ✨ Average the `level` field in the `User` table.
  """
  level_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.level", purpose: QUERY_AVG)
  """
  ✨ Average the `points` field in the `User` table.
  """
  points_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.points", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `level` field in the `User` table.
  """
  level_min: Int @fdc_generated(from: "User.level", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `points` field in the `User` table.
  """
  points_min: Int @fdc_generated(from: "User.points", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `level` field in the `User` table.
  """
  level_max: Int @fdc_generated(from: "User.level", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `points` field in the `User` table.
  """
  points_max: Int @fdc_generated(from: "User.points", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
extend type UserAchievement {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserAchievement", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserAchievement` table.
  """
  _count: Int! @fdc_generated(from: "UserAchievement.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAchievement` table where the `achievementId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  achievementId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAchievement.achievementId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAchievement` table where the `unlockedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unlockedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAchievement.unlockedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserAchievement` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserAchievement.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `unlockedAt` field in the `UserAchievement` table.
  """
  unlockedAt_min: Timestamp @fdc_generated(from: "UserAchievement.unlockedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `unlockedAt` field in the `UserAchievement` table.
  """
  unlockedAt_max: Timestamp @fdc_generated(from: "UserAchievement.unlockedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserAchievement.userId,achievementId", purpose: GLOBAL_ID)
}
